### ISSUE TITLE
Add support for themes using design tokens

### ISSUE THREAD

**Issue by nickwynja** [infor-design/css#194]
**Is your feature request related to a problem? Please describe.**
To prepare for supporting multiple themes on design.infor.com, we should generate multiple themes in IDS-CSS using the token variants.

**Describe the solution you'd like**
Similar to how we handle it in EP, we could have theme variants which import the token variants for regular, dark, and contrast and generate individual stylesheets for each theme.

**Describe alternatives you've considered**
We could also just use tokens within the website to override the IDS-CSS stylesheet locally within the website.

**Additional context**
n/a

**Comment by clepore** [comment]
A future breaking change option is documented here: https://github.com/infor-design/css/issues/197
